name: Listings Checker

on:
  schedule:
    - cron: '0 * * * *'  # every hour at minute 0
  workflow_dispatch:

jobs:
  check-listings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run listings checker
        run: python listings_check.py

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update listings status [bot]"
          file_pattern: |
            listings/perps_listings.json
